### ISSUE TITLE
Formatting code with clang-format

### ISSUE THREAD

**Issue by winterheart** [kevinbentley/Descent3#3]
Hi there.

After some digging in code I would suggest also run `clang-format` on all source files since there a lot code styles mixing and CRLF line endings.

**Comment by kevinbentley** [comment]
Great idea! If someone can do it and submit a PR, that would be great. The sooner the better, before other changes start rolling in.

**Comment by winterheart** [comment]
I can do that, but which format to use? There LLVM, Chromium, Mozilla, Microsoft styles. Here quick comparison: https://github.com/motine/cppstylelineup

Personally I'd prefer LLVM style with 120 line length since it has compact view, but there may be another opinions?

**Comment by JeodC** [comment]
> I can do that, but which format to use? There LLVM, Chromium, Mozilla, Microsoft styles. Here quick comparison: https://github.com/motine/cppstylelineup
> 
> 
> 
> Personally I'd prefer LLVM style with 120 line length since it has compact view, but there may be another opinions?

I've got little experience in reading cpp and the gnu format was the easiest to digest.

**Comment by kevinbentley** [comment]
I think LLVM is reasonable. I've worked with so many different formats over the years, I'm not too particular as long as people make a reasonable attempt at consistency.

**Comment by dsommers** [comment]
This can easily end up as bikesheding ... That said, the [OpenVPN 3 repo](https://github.com/OpenVPN/openvpn3/tree/master/openvpn) has a slightly modified [Microsoft style](https://github.com/OpenVPN/openvpn3/blob/master/.clang-format) which has given us quite reasonable and readable code style.

**Comment by kevinbentley** [comment]
Agreed about bikeshedding. That's why I'm happy to just pick something quick and go. How about the next 10 posts vote and we go with that? I'll vote for LLVM. My personal style when I start a project is closer to the Microsoft style, but with the multiplatform nature of this code (and hopefully, lots of contributors), I think LLVM makes sense.

**Comment by Arcnor** [comment]
So in case it helps (and I know this is not very orthodox, but...), I took the biggest file that's not a script or part of a 3rd party library (which was `multi.cpp`) and asked CLion to generate a format config based on the formatting of that file. This is what it came up with (take into account the whole file probably doesn't match this either):

```
---
Language: Cpp
BasedOnStyle: LLVM
AlignOperands: true
AllowShortBlocksOnASingleLine: false
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: false
BraceWrapping: 
  AfterCaseLabel: true
  AfterClass: false
  AfterControlStatement: true
  AfterEnum: false
  AfterFunction: true
  AfterNamespace: false
  AfterStruct: false
  AfterUnion: false
  AfterExternBlock: false
  BeforeCatch: true
  BeforeElse: true
  BeforeLambdaBody: false
  BeforeWhile: false
  IndentBraces: false
  SplitEmptyFunction: true
  SplitEmptyRecord: true
  SplitEmptyNamespace: true
BreakBeforeBraces: Custom
ColumnLimit: 205
ContinuationIndentWidth: 0
IndentWidth: 4
MaxEmptyLinesToKeep: 100
SpaceBeforeAssignmentOperators: false
SpaceBeforeParens: Always
...
```

Besides this, I also like LLVM :).
